name: "Build"
on:
  push:
    branches:
      - ci-tests
jobs:
  build:
    name: "Build AppleALC"
    runs-on:
      - macos-latest
    steps:
      - name: "Checkout to current repo"
        uses: actions/checkout@v3
      - name: "Run main.py script"
        run: "python3 main.py"
      - name: "Check if AppleALC zip exists"
        if: always()
        run: "ls AppleALC/out/Build/Products/Release"
      - name: "Check if AppleALC was correctly moved"
        if: always()
        run: "ls ../Kexts"
      
      
      #- name: "Upload to artifacts"
      #  if: always()
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: "ocvalidate.txt"
      #    path: "./ocvalidate.txt"
