name: "Build"
on:
  push:
    branches:
      - ci-tests
jobs:
  build:
    name: "Build AppleALC"
    runs-on:
      - macos-latest
    steps:
      - name: "Checkout to current repo"
        uses: actions/checkout@v3
      - name: "Create output dir"
        run: "mkdir ../Kexts"
      - name: "ls"
        run: "ls"
      - name: "Run main.py script"
        run: "python3 main.py -v"
      - name: "ls"
        run: "ls AppleALC"
      
      
      #- name: "Upload to artifacts"
      #  if: always()
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: "ocvalidate.txt"
      #    path: "./ocvalidate.txt"
