name: Build
on:
  push:
    branches:
      - ci-tests
jobs:
  build:
    name: Build AppleALC
    runs-on:
      - macos-latest
    steps:
      - name: Checkout to current repo
        uses: actions/checkout@v3
      - name: Create output directory for built kexts
        run: "mkdir -p work/Kexts"
      - name: Clone AppleALC from source
        run: "git clone https://github.com/acidanthera/AppleALC"
      - name: Remove compressed kern_resources.cpp
        working-directory: AppleALC
        run: "[ ! -e AppleALC/kern_resources.cpp ] && rm -rf AppleALC/AppleALC/kern_resources.cpp"
      - name: Clone MacKernelSDK from source
        working-directory: AppleALC
        run: |
          if [ ! -d MacKernelSDK ]; then
            echo "WARNING: MacKernelSDK doesn't appear to be cloned. Cloning...;"
            git clone https://github.com/acidanthera/MacKernelSDK.git
          fi
      - name: Build Lilu DEBUG from bootstrap.sh
        working-directory: AppleALC
        run: |
          if [ ! -d "Lilu.kext" ]; then
            echo "WARNING: Lilu debug doesn't appear to be there. Building...";
            wget https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh  > /dev/null 2>&1
            bash bootstrap.sh
          fi
      - name: Create a temporarily Resources folder
        working-directory: AppleALC
        run: |
          mv Resources Resources_bak
          mkdir Resources
          mv Resources_bak/PinConfigs.kext Resources
          mv Resources_bak/Controllers.plist Resources
          mv Resources_bak/Kexts.plist Resources
          mv Resources_bak/Vendors.plist Resources
      - name: Echoes available codecs
        working-directory: AppleALC

        env:
          codecs: ls Resources_bak
        run: echo $codecs
      #- name: Upload to artifacts
      #  if: always()
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ocvalidate.txt
      #    path: ./ocvalidate.txt
