name: Docs
on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    name: Generate AppleALC layout ids MarkDown files
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout to current repo
        uses: actions/checkout@v3
      - name: Create output directory for built kexts
        run: mkdir -p mds/{AnalogDevices,CirrusLogic,Conexant,Creative,IDT,Realtek,SigmaTel,VIA}
      - name: Clone AppleALC from source
        run: git clone https://github.com/acidanthera/AppleALC
      - name: Get AppleALC latest stable release
        id: applealc-latest-release
        working-directory: AppleALC
        run: echo "::set-output name=tag-name::$(git describe --tags `git rev-list --tags --max-count=1`)"
      - name: Checkout to AppleALC latest stable release
        working-directory: AppleALC
        run: git checkout ${{ steps.applealc-latest-release.outputs.tag-name }}
      - name: Generate .md files
        run: |
          cp .assets/scripts/{json2md.py,layout_id_finder.py} AppleALC
          cd AppleALC
          rm *.md
          python3 layout_id_finder.py
          python3 json2md.py
          mv *.md ../mds
      - name: Move .md files onto their respective directories
        working-directory: mds
        run: |
          mv AD*.md AnalogDevices
          mv CS*.md CirrusLogic
          mv CX*.md Conexant
          mv CA*.md Creative
          mv IDT*.md IDT
          mv ALC*.md Realtek
          mv STAC*.md SigmaTel
          mv VT*.md VIA
          rm -rf ../{AnalogDevices,CirrusLogic,Conexant,Creative,IDT,Realtek,SigmaTel,VIA}
          mv * ../
      - name: Remove AppleALC directory
        run: rm -rf AppleALC
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          commit-message: Update layout ids
          body: |
            Updated layout-ids
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          title: Update layout-ids